In [2]:
!pip install numpy

  Using cached numpy-2.2.5-cp310-cp310-win_amd64.whl (12.9 MB)



[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# Import the NumPy library with its standard alias
import numpy as np

## 1. From Python Structures (Lists, Tuples)

- Using np.array() - The most fundamental way.
- It infers the data type unless specified

#### - Create a array from a list of lists (matrix)
##### Create a 1D array from a list

In [96]:
list_1d = [1, 2, 3, 4, 5]
arr_1d = np.array(list_1d)

print("1D array from list:\n", arr_1d)
print("Data type:", arr_1d.dtype) # Output: int64 (or int32 depending on system)
print("-" * 20)

1D array from list:
 [1 2 3 4 5]
Data type: int64
--------------------


##### Create a 2D array from a list

In [95]:
list_2d = [1, 2, 3], [4, 5, 6]
arr_2d = np.array(list_2d)

print("2D array from list of lists:\n", arr_2d)
print("Shape:", arr_2d.shape) # Output: (2, 3) -> 2 rows, 3 columns
print("-" * 20)

2D array from list of lists:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
--------------------


##### Create a 3D array from a list

In [94]:
list_3d = [1, 2, 3], [4, 5, 6], [7, 8, 9]
arr_3d = np.array(list_3d)

print("3D array from list of lists:\n", arr_3d)
print("Shape:", arr_3d.shape) # Output: (3, 3) -> 3 rows, 3 columns
print("-" * 20)

3D array from list of lists:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
--------------------


#### - Create an array from a tuple

In [93]:
tuple_1 = (10, 20, 30)
array_from_tuple = np.array(tuple_1)

print("Array from tuple:\n", array_from_tuple)
print("-" * 20)

Array from tuple:
 [10 20 30]
--------------------


#### - Specify the data type during creation

In [23]:
arr_float = np.array([1, 2, 3], dtype = np.float64)

print("Array with specified float dtype:\n ", arr_float)
print("Data type: ", arr_float.dtype)

Array with specified float dtype:
  [1. 2. 3.]
Data type:  float64


In [92]:
arr_complex = np.array([1+2j, 3+4j], dtype=np.complex128)

print("Array with specified complex dtype:\n", arr_complex)
print("Data type:", arr_complex.dtype) # Output: complex128
print("-" * 20)

Array with specified complex dtype:
 [1.+2.j 3.+4.j]
Data type: complex128
--------------------


## 2. Intrinsic Creation Functions (Array Generators)
#### np.arange()
- np.arange(): Like Python's range, but returns an array
- **np.arange(start, stop, step)** - 'stop' is exclusive

In [28]:
arr_range = np.arange(10)
print("np.arange(10): \n", arr_range)

np.arange(10): 
 [0 1 2 3 4 5 6 7 8 9]


In [29]:
arr_range_step = np.arange(0, 10, 2)
print("np.arange(0, 10, 2): \n", arr_range_step)

np.arange(0, 10, 2): 
 [0 2 4 6 8]


In [91]:
arr_range_float = np.arange(0.0, 1.0, 0.2) # Floats work too
print("np.arange(0.0, 1.0, 0.2):\n", arr_range_float)
print("-" * 20)

np.arange(0.0, 1.0, 0.2):
 [0.  0.2 0.4 0.6 0.8]
--------------------


#### np.linspace()
- np.linspace(): Evenly spaced numbers over a specified interval
- **np.linspace(start, stop, num)** - 'stop' is *inclusive* by default
- 'num' is the number of points to generate

In [33]:
arr_linspace = np.linspace(0, 20, 5) # 5 numbers from 0 to 10 (inclusive)
print("np.linspace(0, 20, 5): \n", arr_linspace)

np.linspace(0, 20, 5): 
 [ 0.  5. 10. 15. 20.]


In [90]:
arr_linspace_excl = np.linspace(0, 20, 5, endpoint=False) # Exclude endpoint
print("np.linspace(0, 20, 5, endpoint=False): \n", arr_linspace_excl)
print("-" * 20)

np.linspace(0, 20, 5, endpoint=False): 
 [ 0.  4.  8. 12. 16.]
--------------------


#### np.zeros()
- np.zeros(): Array filled with zeros
- Takes a shape tuple as input

In [37]:
zeros_1d = np.zeros(5) # 1D array of 5 zeros
print("np.zeros(5):\n", zeros_1d)

np.zeros(5):
 [0. 0. 0. 0. 0.]


In [39]:
zeros_2d = np.zeros((2, 4)) # 2x4 array of zeros
print("np.zeros((2, 4)):\n", zeros_2d)

np.zeros((2, 4)):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
print("Data type (default):", zeros_2d.dtype) # Default is float64

Data type (default): float64


In [89]:
zeros_int = np.zeros((3, 2), dtype = np.int32) # Specify integer type
print("np.zeros((3, 2), dtype = np.int32): \n", zeros_int)
print("Data type (specified): ", zeros_int.dtype)
print("-" * 20)

np.zeros((3, 2), dtype = np.int32): 
 [[0 0]
 [0 0]
 [0 0]]
Data type (specified):  int32
--------------------


#### np.ones()
- np.ones(): Array filled with ones
- Takes a shape tuple as input

In [62]:
ones_1d = np.ones(3)
print("np.ones(3):\n", ones_1d)

np.ones(3):
 [1. 1. 1.]


In [63]:
ones_3d = np.ones((2, 3, 2)) # 3D array (2 matrices of 3x2)
print("np.ones((2, 3, 2)):\n", ones_3d)
print("Data type (default):", ones_3d.dtype) # Default is float64

np.ones((2, 3, 2)):
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
Data type (default): float64


In [88]:
ones_3d.shape
print("-" * 20)

--------------------


#### np.full()
- np.full(): Array filled with a specific value
- **np.full(shape, fill_value)**

In [74]:
full_arr = np.full((2, 5), 10.1) # 2x5 array filled with 7.5
print("np.full((2, 5), 10.1):\n", full_arr)

np.full((2, 5), 10.1):
 [[10.1 10.1 10.1 10.1 10.1]
 [10.1 10.1 10.1 10.1 10.1]]


In [75]:
full_str = np.full(3, "hello") # Can fill with other types too
print("np.full(3, 'hello'):\n", full_str)

np.full(3, 'hello'):
 ['hello' 'hello' 'hello']


In [77]:
full_str_1 = np.full((3,3), "hi") # Can fill with other types too
print("np.full((3,3), 'hi'):\n", full_str_1)

np.full((3,3), 'hi'):
 [['hi' 'hi' 'hi']
 ['hi' 'hi' 'hi']
 ['hi' 'hi' 'hi']]


In [80]:
print("Data type:", full_str.dtype) # Inferred dtype ('<U5' for unicode string length 5)
print("-" * 20)

Data type: <U5
--------------------


#### np.eye()
- np.eye(): Creates a 2D identity matrix (1s on diagonal, 0s elsewhere)
- **np.eye(N, M=None, k=0)**
- N: number of rows
- M: number of columns (defaults to N)
- k: index of the diagonal (0=main, positive=upper, negative=lower)

In [81]:
eye_mat = np.eye(4) # 4x4 identity matrix
print("np.eye(4):\n", eye_mat)

np.eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [86]:
eye_mat_k1 = np.eye(4, k=1) # Diagonal offset by 1 (upper)
print("np.eye(4, k=1):\n", eye_mat_k1)

np.eye(4, k=1):
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [87]:
eye_mat_rect = np.eye(3, 5) # Rectangular matrix (3x5)
print("np.eye(3, 5):\n", eye_mat_rect)
print("-" * 20)

np.eye(3, 5):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
--------------------


#### np.identity()
- np.identity(): Similar to eye, but specifically for square identity matrices (k=0)

In [99]:
identity_mat = np.identity(3) # 3x3 identity matrix
print("np.identity(3):\n", identity_mat)
print("-" * 20)

np.identity(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
--------------------


#### np.empty()
- np.empty(): Creates an "empty" array with the given shape.
- The initial content is arbitrary and depends on the memory state.
- Useful when you plan to fill the array later and want to skip zero initialization.

In [100]:
empty_arr = np.empty((2, 3))
print("np.empty((2, 3)) (values are uninitialized):\n", empty_arr)
print("-" * 20)

np.empty((2, 3)) (values are uninitialized):
 [[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]
--------------------


In [101]:
# _like functions: Create arrays with the same shape and dtype as another array
existing_arr = np.array([[1, 2], [3, 4]], dtype=np.float32)
print("Existing array:\n", existing_arr)
print("Shape:", existing_arr.shape, "Dtype:", existing_arr.dtype)

Existing array:
 [[1. 2.]
 [3. 4.]]
Shape: (2, 2) Dtype: float32


In [102]:
zeros_like_arr = np.zeros_like(existing_arr)
print("np.zeros_like(existing_arr):\n", zeros_like_arr)
print("Shape:", zeros_like_arr.shape, "Dtype:", zeros_like_arr.dtype)

np.zeros_like(existing_arr):
 [[0. 0.]
 [0. 0.]]
Shape: (2, 2) Dtype: float32


In [103]:
ones_like_arr = np.ones_like(existing_arr)
print("np.ones_like(existing_arr):\n", ones_like_arr)
print("Shape:", ones_like_arr.shape, "Dtype:", ones_like_arr.dtype)

np.ones_like(existing_arr):
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2) Dtype: float32


In [104]:
full_like_arr = np.full_like(existing_arr, -1)
print("np.full_like(existing_arr, -1):\n", full_like_arr)
print("Shape:", full_like_arr.shape, "Dtype:", full_like_arr.dtype)

np.full_like(existing_arr, -1):
 [[-1. -1.]
 [-1. -1.]]
Shape: (2, 2) Dtype: float32


In [105]:
empty_like_arr = np.empty_like(existing_arr)
print("np.empty_like(existing_arr) (uninitialized):\n", empty_like_arr)
print("Shape:", empty_like_arr.shape, "Dtype:", empty_like_arr.dtype)
print("-" * 20)

np.empty_like(existing_arr) (uninitialized):
 [[1. 1.]
 [1. 1.]]
Shape: (2, 2) Dtype: float32
--------------------


## 3. Random Number Generation (np.random module)

In [106]:
# np.random.seed(): Makes random number generation predictable (reproducible)
# Call this before generating random numbers if you need the same sequence again

np.random.seed(42) # Use any integer as the seed

#### np.random.rand()
- np.random.rand(d0, d1, ..., dn): Random values in a given shape from a
- uniform distribution over [0, 1).

In [114]:
rand_arr = np.random.rand(3, 2) # 3x2 array of random floats between 0 and 1
print("np.random.rand(3, 2):\n", rand_arr)
print("-" * 20)

np.random.rand(3, 2):
 [[0.42340148 0.39488152]
 [0.29348817 0.01407982]
 [0.1988424  0.71134195]]
--------------------


#### np.random.randn()
- np.random.randn(d0, d1, ..., dn): Random values in a given shape from the
- "standard normal" distribution (mean 0, variance 1).

In [116]:
randn_arr = np.random.randn(5) # 1D array of 5 samples from standard normal
print("np.random.randn(5):\n", randn_arr)

randn_arr_2d = np.random.randn(2, 4) # 2x4 array
print("np.random.randn(2, 4):\n", randn_arr_2d)
print("-" * 20)

np.random.randn(5):
 [-0.08111895  0.46779475  0.73612235 -0.77970188 -0.84389636]
np.random.randn(2, 4):
 [[-0.15053386 -0.96555767  0.15048908 -0.11342125]
 [ 2.63352822 -1.02509089 -0.78204783  0.42394307]]
--------------------


#### np.random.randint()
- np.random.randint(low, high=None, size=None, dtype=int): Random integers.
- If high is None, range is [0, low).
- If high is specified, range is [low, high).
- size specifies the output shape.


In [117]:
randint_arr1 = np.random.randint(10, size=5) # 5 random ints from [0, 10)
print("np.random.randint(10, size=5):\n", randint_arr1)
randint_arr2 = np.random.randint(50, 100, size=(2, 3)) # 2x3 array, ints from [50, 100)
print("np.random.randint(50, 100, size=(2, 3)):\n", randint_arr2)
print("-" * 20)

np.random.randint(10, size=5):
 [6 3 6 2 5]
np.random.randint(50, 100, size=(2, 3)):
 [[77 51 91]
 [94 55 77]]
--------------------


#### np.random.choice()
- np.random.choice(a, size=None, replace=True, p=None): Generates a random sample

In [124]:
# from a given 1-D array 'a'.
elements = np.array(['a', 'b', 'c', 'd', 'e'])
choices = np.random.choice(elements, size=3) # Sample 3 elements with replacement
print("np.random.choice(elements, size=3):\n", choices)

np.random.choice(elements, size=3):
 ['e' 'a' 'c']


In [128]:
choices_no_replace = np.random.choice(elements, size=3, replace=False) # Sample without replacement
print("np.random.choice(elements, size=3, replace=False):\n", choices_no_replace)

np.random.choice(elements, size=3, replace=False):
 ['e' 'd' 'a']


In [130]:
# Specifying probabilities 'p' for each element in 'a'
probabilities = [0.1, 0.1, 0.5, 0.1, 0.2] # Probabilities must sum to 1
choices_prob = np.random.choice(elements, size=10, p=probabilities)
print("np.random.choice with probabilities:\n", choices_prob)
print("-" * 20)

np.random.choice with probabilities:
 ['e' 'c' 'c' 'd' 'c' 'd' 'c' 'c' 'c' 'c']
--------------------


In [131]:
# Other distributions are available, e.g., normal (Gaussian) with specified mean/std dev
mu, sigma = 0, 0.1 # mean and standard deviation
normal_samples = np.random.normal(mu, sigma, size=5)
print(f"np.random.normal(mu={mu}, sigma={sigma}, size=5):\n", normal_samples)
print("-" * 20)

np.random.normal(mu=0, sigma=0.1, size=5):
 [-0.09905363 -0.05662977  0.00996514 -0.05034757 -0.15506634]
--------------------


In [135]:
# Resetting the seed will reproduce the *entire sequence* from that point
np.random.seed(42)
print("First rand call after resetting seed(42):\n", np.random.rand(3, 2))
np.random.seed(42)
print("Second rand call after resetting seed(42):\n", np.random.rand(3, 2)) # Same as first

First rand call after resetting seed(42):
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
Second rand call after resetting seed(42):
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
