In [1]:
import numpy as np

In [2]:
# --- Create Sample Arrays ---

arr_1d = np.arange(10) # [0 1 2 3 4 5 6 7 8 9]
print("1D Array (arr_1d):\n", arr_1d)

1D Array (arr_1d):
 [0 1 2 3 4 5 6 7 8 9]


In [8]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("\n2D Array (arr_2d):\n", arr_2d)
print("-" * 30)


2D Array (arr_2d):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------


## 1. Basic Indexing (Accessing Single Elements)
Uses zero-based integer indices

In [15]:
# 1D Array

element_1d = arr_1d[3] # Get the element at index 3
print(f"arr_1d[3]: {element_1d}") # Output: 3

arr_1d[3]: 3


In [13]:
# 2D Array
# Use comma-separated indices: arr[row_index, column_index]

element_2d = arr_2d[1, 2] # Get element in row 1, column 2
print(f"\narr_2d[1, 2]: {element_2d}") # Output: 7


arr_2d[1, 2]: 7


In [14]:
# Can also use chained brackets (less efficient, generally avoid for single elements)

element_2d_chained = arr_2d[1][2]
print(f"arr_2d[1][2]: {element_2d_chained}") # Output: 7
print("-" * 30)

arr_2d[1][2]: 7
------------------------------


## 2. Slicing (Extracting Subarrays)

- Syntax: **start:stop:step** (stop is exclusive)
- Omitting start defaults to 0, omitting stop defaults to end, omitting step defaults to 1

#### 1D Array Slicing

In [24]:
slice_1d_1 = arr_1d[2:6] # Elements from index 2 up to (not including) 6
print(f"arr_1d[2:6]: {slice_1d_1}") # Output: [2 3 4 5]

arr_1d[2:6]: [2 3 4 5]


In [20]:
slice_1d_2 = arr_1d[:4] # Elements from the beginning up to index 4
print(f"arr_1d[:4]: {slice_1d_2}") # Output: [0 1 2 3]

arr_1d[:4]: [0 1 2 3]


In [21]:
slice_1d_3 = arr_1d[5:] # Elements from index 5 to the end
print(f"arr_1d[5:]: {slice_1d_3}") # Output: [5 6 7 8 9]

arr_1d[5:]: [5 6 7 8 9]


In [22]:
slice_1d_step = arr_1d[0:8:2] # Elements from index 0 to 8, step 2
print(f"arr_1d[0:8:2]: {slice_1d_step}") # Output: [0 2 4 6]

arr_1d[0:8:2]: [0 2 4 6]


In [23]:
slice_1d_reverse = arr_1d[::-1] # Reverse the array
print(f"arr_1d[::-1]: {slice_1d_reverse}") # Output: [9 8 7 6 5 4 3 2 1 0]

arr_1d[::-1]: [9 8 7 6 5 4 3 2 1 0]


#### 2D Array Slicing

In [28]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("\n2D Array (arr_2d):\n", arr_2d)


2D Array (arr_2d):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [50]:
# Apply slicing to each dimension, separated by commas: arr[row_slice, col_slice]

# Get the first two rows (rows 0 and 1)
slice_2d_rows = arr_2d[0:2]
print(f"\narr_2d[0:2]:\n{slice_2d_rows}")


arr_2d[0:2]:
[[1 2 3 4]
 [5 6 7 8]]


In [51]:
# Get columns 1 and 2 from all rows
slice_2d_cols = arr_2d[:, 1:3]
print(f"\narr_2d[:, 1:3]:\n{slice_2d_cols}")


arr_2d[:, 1:3]:
[[ 2  3]
 [ 6  7]
 [10 11]]


In [52]:
# Get rows from index 1 onwards, columns from index 2 onwards
slice_2d_submatrix = arr_2d[1:, 2:]
print(f"\narr_2d[1:, 2:]:\n{slice_2d_submatrix}")


arr_2d[1:, 2:]:
[[ 7  8]
 [11 12]]


## 3. Integer Array Indexing (Fancy Indexing)
- Use arrays of integers to select specific elements, rows, or columns.
- This *always* returns a COPY of the data, not a view.

#### 1D Array

In [55]:
indices_1d = np.array([1, 4, 5, 8])
fancy_1d = arr_1d[indices_1d] # Select elements at these specific indices

print(f"arr_1d[[1, 4, 5, 8]]: {fancy_1d}")

arr_1d[[1, 4, 5, 8]]: [1 4 5 8]


#### 2D Array - Selecting specific rows

In [56]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("\n2D Array (arr_2d):\n", arr_2d)


2D Array (arr_2d):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [61]:
row_indices = np.array([0, 2])
fancy_rows = arr_2d[row_indices] # Select rows 0 and 2

print(f"\narr_2d[[0, 2]] (selecting rows):\n{fancy_rows}")


arr_2d[[0, 2]] (selecting rows):
[[ 1  2  3  4]
 [ 9 10 11 12]]


In [64]:
# 2D Array - Selecting specific elements using coordinate pairs
# Provide tuples or arrays for row and column indices
row_coords = np.array([0, 1, 2])
col_coords = np.array([1, 3, 0])

fancy_elements = arr_2d[row_coords, col_coords] # Select elements (0,1), (1,3), (2,0)
print(f"\narr_2d[[0, 1, 2], [1, 3, 0]]: {fancy_elements}") # Output: [ 2  8  9]


arr_2d[[0, 1, 2], [1, 3, 0]]: [2 8 9]


In [65]:
# Selecting specific columns (a bit more complex with just fancy indexing)
# Often combined with slicing:
col_indices = np.array([0, 3])
fancy_cols = arr_2d[:, col_indices] # Select columns 0 and 3 from all rows
print(f"\narr_2d[:, [0, 3]] (selecting columns):\n{fancy_cols}")
# Output:
# [[ 1  4]
#  [ 5  8]
#  [ 9 12]]


arr_2d[:, [0, 3]] (selecting columns):
[[ 1  4]
 [ 5  8]
 [ 9 12]]


#### 4. Boolean Array Indexing (Masking)
- Use boolean arrays (masks) to select elements where the mask is True.
- The mask must have the same shape as the dimension it's indexing, or be broadcastable.
- This also returns a COPY of the data.

In [66]:
print("--- Boolean Array Indexing (Masking) ---")
# Create a boolean mask based on a condition
mask = arr_1d > 5
print(f"Mask (arr_1d > 5): {mask}") # Output: [F F F F F F T T T T] (F=False, T=True)

# Apply the mask
masked_1d = arr_1d[mask]
print(f"arr_1d[arr_1d > 5]: {masked_1d}") # Output: [6 7 8 9]

# Combine conditions using logical operators (& for AND, | for OR, ~ for NOT)
mask_combined = (arr_1d > 2) & (arr_1d < 7)
print(f"\nMask ((arr_1d > 2) & (arr_1d < 7)): {mask_combined}")
masked_combined_1d = arr_1d[mask_combined]
print(f"arr_1d[(arr_1d > 2) & (arr_1d < 7)]: {masked_combined_1d}") # Output: [3 4 5 6]

# Masking on 2D arrays
mask_2d = arr_2d % 2 == 0 # Select even numbers
print(f"\nMask (arr_2d % 2 == 0):\n{mask_2d}")
masked_2d = arr_2d[mask_2d] # Returns a 1D array of the selected elements
print(f"arr_2d[arr_2d % 2 == 0]: {masked_2d}") # Output: [ 2  4  6  8 10 12]

# Select rows based on a condition on a specific column
# Example: Select rows where the first column (index 0) is greater than 1
mask_rows = arr_2d[:, 0] > 1
print(f"\nMask for rows (arr_2d[:, 0] > 1): {mask_rows}") # Output: [False True True]
selected_rows = arr_2d[mask_rows] # Select rows where the mask is True
# selected_rows = arr_2d[arr_2d[:, 0] > 1] # Equivalent shorter form
print(f"arr_2d[arr_2d[:, 0] > 1] (selecting rows):\n{selected_rows}")
# Output:
# [[ 5  6  7  8]
#  [ 9 10 11 12]]
print("-" * 30)

--- Boolean Array Indexing (Masking) ---
Mask (arr_1d > 5): [False False False False False False  True  True  True  True]
arr_1d[arr_1d > 5]: [6 7 8 9]

Mask ((arr_1d > 2) & (arr_1d < 7)): [False False False  True  True  True  True False False False]
arr_1d[(arr_1d > 2) & (arr_1d < 7)]: [3 4 5 6]

Mask (arr_2d % 2 == 0):
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
arr_2d[arr_2d % 2 == 0]: [ 2  4  6  8 10 12]

Mask for rows (arr_2d[:, 0] > 1): [False  True  True]
arr_2d[arr_2d[:, 0] > 1] (selecting rows):
[[ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------


#### 5. Combining Indexing Types
- You can mix slicing, basic indexing, fancy indexing, and boolean indexing.

In [67]:
# Select specific columns (1 and 3) from the first two rows (0 and 1)
combined_slice_fancy = arr_2d[0:2, [1, 3]]
print(f"arr_2d[0:2, [1, 3]]:\n{combined_slice_fancy}")
# Output:
# [[2 4]
#  [6 8]]

# Select elements greater than 10 from the last row
last_row = arr_2d[-1] # Basic indexing to get the last row
print(f"\nLast row: {last_row}")
combined_bool = last_row[last_row > 10] # Boolean indexing on the selected row
print(f"Elements > 10 in last row: {combined_bool}") # Output: [11 12]

# Equivalent in one step:
combined_bool_direct = arr_2d[-1, arr_2d[-1] > 10]
print(f"arr_2d[-1, arr_2d[-1] > 10]: {combined_bool_direct}") # Output: [11 12]
print("-" * 30)

arr_2d[0:2, [1, 3]]:
[[2 4]
 [6 8]]

Last row: [ 9 10 11 12]
Elements > 10 in last row: [11 12]
arr_2d[-1, arr_2d[-1] > 10]: [11 12]
------------------------------


#### 6. Views vs. Copies
- IMPORTANT: Understanding the difference is crucial to avoid unexpected behavior.

In [68]:
# Slicing creates a VIEW: Changes to the view WILL affect the original array.
arr_slice = arr_1d[2:5] # [2 3 4]
print(f"Original slice (arr_slice): {arr_slice}")
print(f"Original array (arr_1d) before modification: {arr_1d}")

arr_slice[0] = 99 # Modify the first element of the slice
print(f"\nModified slice: {arr_slice}") # Output: [99 3 4]
print(f"Original array (arr_1d) AFTER modification: {arr_1d}") # Output: [ 0  1 99  3  4  5  6  7  8  9] - Original is changed!

# Restore original arr_1d
arr_1d[2] = 2
print(f"\nRestored arr_1d: {arr_1d}")

# Fancy Indexing and Boolean Indexing create COPIES: Changes to the copy DO NOT affect the original.
arr_fancy = arr_1d[[1, 3, 5]] # [1 3 5]
print(f"\nOriginal fancy indexed array (arr_fancy): {arr_fancy}")
print(f"Original array (arr_1d) before modification: {arr_1d}")

arr_fancy[0] = 88 # Modify the first element of the fancy indexed array
print(f"\nModified fancy indexed array: {arr_fancy}") # Output: [88 3 5]
print(f"Original array (arr_1d) AFTER modification: {arr_1d}") # Output: [0 1 2 3 4 5 6 7 8 9] - Original is UNCHANGED!

# To explicitly create a copy when slicing (or from any array), use the .copy() method
arr_slice_copy = arr_1d[2:5].copy()
print(f"\nOriginal slice copy (arr_slice_copy): {arr_slice_copy}")
print(f"Original array (arr_1d) before modification: {arr_1d}")

arr_slice_copy[0] = 77 # Modify the copy
print(f"\nModified slice copy: {arr_slice_copy}") # Output: [77 3 4]
print(f"Original array (arr_1d) AFTER modification: {arr_1d}") # Output: [0 1 2 3 4 5 6 7 8 9] - Original is UNCHANGED!
print("-" * 30)

Original slice (arr_slice): [2 3 4]
Original array (arr_1d) before modification: [0 1 2 3 4 5 6 7 8 9]

Modified slice: [99  3  4]
Original array (arr_1d) AFTER modification: [ 0  1 99  3  4  5  6  7  8  9]

Restored arr_1d: [0 1 2 3 4 5 6 7 8 9]

Original fancy indexed array (arr_fancy): [1 3 5]
Original array (arr_1d) before modification: [0 1 2 3 4 5 6 7 8 9]

Modified fancy indexed array: [88  3  5]
Original array (arr_1d) AFTER modification: [0 1 2 3 4 5 6 7 8 9]

Original slice copy (arr_slice_copy): [2 3 4]
Original array (arr_1d) before modification: [0 1 2 3 4 5 6 7 8 9]

Modified slice copy: [77  3  4]
Original array (arr_1d) AFTER modification: [0 1 2 3 4 5 6 7 8 9]
------------------------------
