In [1]:
import numpy as np

In [11]:
arr1 = np.array([1, 2,3, 4])
arr2 = np.array([10, 20, 30, 40])

arr_2d_a = np.array([[1, 2], [3, 4]])
arr_2d_b = np.array([[5, 6], [7, 8]])

arr_mixed = np.array([-2, -1, 0, 1, 2, 3])

arr_bool1 = np.array([True, False, True, False])
arr_bool2 = np.array([True, True, False, False])

arr_large = np.arange(1, 10)
arr_large_reshape = np.arange(1, 10).reshape(3, 3)

In [14]:
print(f"arr1: {arr1}\n")
print(f"arr2: {arr2}\n")
print(f"arr_2d_a:\n{arr_2d_a}\n")
print(f"arr_2d_b:\n{arr_2d_b}\n")
print(f"arr_mixed: {arr_mixed}\n")
print(f"arr_bool1: {arr_bool1}\n")
print(f"arr_bool2: {arr_bool2}\n")
print(f"arr_large:\n{arr_large}\n")
print(f"arr_large:\n{arr_large_reshape}\n")

arr1: [1 2 3 4]

arr2: [10 20 30 40]

arr_2d_a:
[[1 2]
 [3 4]]

arr_2d_b:
[[5 6]
 [7 8]]

arr_mixed: [-2 -1  0  1  2  3]

arr_bool1: [ True False  True False]

arr_bool2: [ True  True False False]

arr_large:
[1 2 3 4 5 6 7 8 9]

arr_large:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



## 1. Vectorization
- NumPy operations are vectorized, meaning they operate on entire arrays
- element by element without needing explicit Python loops. This is much faster.

In [15]:
# Instead of:
# result = []
# for i in range(len(arr1)):
#     result.append(arr1[i] + arr2[i])
# result = np.array(result)

In [16]:
# We can do:
result_vectorized = arr1 + arr2 # Simple, concise, and fast!

print(f"Result: {result_vectorized}") # Output: [11 22 33 44]

Result: [11 22 33 44]


#### 2. Element-wise Arithmetic Operations
- Standard operators (+, -, *, /, //, %, **) work element-wise

In [17]:
print("--- Element-wise Arithmetic ---")
print(f"arr1 + arr2 = {arr1 + arr2}")       # Addition
print(f"arr1 - arr2 = {arr1 - arr2}")       # Subtraction
print(f"arr1 * arr2 = {arr1 * arr2}")       # Multiplication
print(f"arr2 / arr1 = {arr2 / arr1}")       # Division (float result)
print(f"arr2 // arr1 = {arr2 // arr1}")      # Floor Division (integer result)
print(f"arr2 % arr1 = {arr2 % arr1}")       # Modulus (remainder)
print(f"arr1 ** 2 = {arr1 ** 2}")           # Exponentiation

--- Element-wise Arithmetic ---
arr1 + arr2 = [11 22 33 44]
arr1 - arr2 = [ -9 -18 -27 -36]
arr1 * arr2 = [ 10  40  90 160]
arr2 / arr1 = [10. 10. 10. 10.]
arr2 // arr1 = [10 10 10 10]
arr2 % arr1 = [0 0 0 0]
arr1 ** 2 = [ 1  4  9 16]


In [18]:
# Works on multi-dimensional arrays too (if shapes are compatible)
print(f"\narr_2d_a * arr_2d_b:\n{arr_2d_a * arr_2d_b}")


arr_2d_a * arr_2d_b:
[[ 5 12]
 [21 32]]


In [19]:
# Operations with scalars are broadcast (discussed later)
print(f"\narr1 + 100 = {arr1 + 100}") # Output: [101 102 103 104]
print(f"arr_2d_a * 3 = \n{arr_2d_a * 3}")


arr1 + 100 = [101 102 103 104]
arr_2d_a * 3 = 
[[ 3  6]
 [ 9 12]]


#### 3. Element-wise Comparison Operations
- Return boolean arrays

In [20]:
print("--- Element-wise Comparisons ---")
print(f"arr1 > 2: {arr1 > 2}")           # Greater than
print(f"arr2 <= 30: {arr2 <= 30}")       # Less than or equal to
print(f"arr1 == arr1: {arr1 == arr1}")   # Equal to
print(f"arr1 != arr2: {arr1 != arr2}")   # Not equal to

--- Element-wise Comparisons ---
arr1 > 2: [False False  True  True]
arr2 <= 30: [ True  True  True False]
arr1 == arr1: [ True  True  True  True]
arr1 != arr2: [ True  True  True  True]


In [21]:
# Comparing arrays element-wise
print(f"arr1 == np.array([1, 99, 3, 99]): {arr1 == np.array([1, 99, 3, 99])}")
print("-" * 30)

arr1 == np.array([1, 99, 3, 99]): [ True False  True False]
------------------------------


#### 4. Logical Operations
- Operate on boolean arrays or arrays evaluated in boolean context

In [24]:
print("--- Logical Operations ---")
# Use np.logical_and, np.logical_or, np.logical_not
# (Python's 'and', 'or', 'not' work on single boolean values, not arrays element-wise)
print(f"arr_bool1: {arr_bool1}")
print(f"arr_bool2: {arr_bool2}\n")

print(f"np.logical_and(arr_bool1, arr_bool2): {np.logical_and(arr_bool1, arr_bool2)}")
print(f"np.logical_or(arr_bool1, arr_bool2): {np.logical_or(arr_bool1, arr_bool2)}")
print(f"np.logical_not(arr_bool1): {np.logical_not(arr_bool1)}")

--- Logical Operations ---
arr_bool1: [ True False  True False]
arr_bool2: [ True  True False False]

np.logical_and(arr_bool1, arr_bool2): [ True False False False]
np.logical_or(arr_bool1, arr_bool2): [ True  True  True False]
np.logical_not(arr_bool1): [False  True False  True]


#### 5. Universal Functions (ufuncs)
- Functions that operate element-wise on ndarrays.
- Many standard math functions have ufunc equivalents.

In [25]:
# Arithmetic ufuncs (often equivalent to operators)
print(f"np.add(arr1, arr2): {np.add(arr1, arr2)}")
print(f"np.subtract(arr2, arr1): {np.subtract(arr2, arr1)}")
print(f"np.multiply(arr1, 10): {np.multiply(arr1, 10)}")
print(f"np.divide(arr2, arr1): {np.divide(arr2, arr1)}")
print(f"np.sqrt(arr1): {np.sqrt(arr1)}") # Square root
print(f"np.power(arr1, 3): {np.power(arr1, 3)}") # Exponentiation
print(f"np.abs(arr_mixed): {np.abs(arr_mixed)}") # Absolute value

np.add(arr1, arr2): [11 22 33 44]
np.subtract(arr2, arr1): [ 9 18 27 36]
np.multiply(arr1, 10): [10 20 30 40]
np.divide(arr2, arr1): [10. 10. 10. 10.]
np.sqrt(arr1): [1.         1.41421356 1.73205081 2.        ]
np.power(arr1, 3): [ 1  8 27 64]
np.abs(arr_mixed): [2 1 0 1 2 3]


In [26]:
# Trigonometric functions (expect radians)
angles = np.linspace(0, np.pi, 5) # 0, pi/4, pi/2, 3pi/4, pi
print(f"\nAngles (radians): {angles}")
print(f"np.sin(angles): {np.sin(angles)}")
print(f"np.cos(angles): {np.cos(angles)}")
print(f"np.tan(angles): {np.tan(angles)}")

# Exponential and Logarithmic
print(f"\nnp.exp(arr1): {np.exp(arr1)}") # e^x
print(f"np.log(arr1): {np.log(arr1)}") # Natural log (ln)
print(f"np.log10(arr2): {np.log10(arr2)}") # Base-10 log
print(f"np.log2(arr1): {np.log2(arr1)}") # Base-2 log


Angles (radians): [0.         0.78539816 1.57079633 2.35619449 3.14159265]
np.sin(angles): [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
np.cos(angles): [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
np.tan(angles): [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]

np.exp(arr1): [ 2.71828183  7.3890561  20.08553692 54.59815003]
np.log(arr1): [0.         0.69314718 1.09861229 1.38629436]
np.log10(arr2): [1.         1.30103    1.47712125 1.60205999]
np.log2(arr1): [0.        1.        1.5849625 2.       ]


In [27]:
# Rounding
float_arr = np.array([1.2, 2.7, 3.5, 4.1, -1.6])
print(f"\nFloat array: {float_arr}")
print(f"np.round(float_arr): {np.round(float_arr)}") # Round to nearest int (0.5 rounds to even)
print(f"np.floor(float_arr): {np.floor(float_arr)}") # Round down
print(f"np.ceil(float_arr): {np.ceil(float_arr)}") # Round up
print(f"np.trunc(float_arr): {np.trunc(float_arr)}") # Truncate towards zero

# More ufuncs exist: np.isnan, np.isinf, np.sign, np.maximum, np.minimum, etc.
print("-" * 30)



Float array: [ 1.2  2.7  3.5  4.1 -1.6]
np.round(float_arr): [ 1.  3.  4.  4. -2.]
np.floor(float_arr): [ 1.  2.  3.  4. -2.]
np.ceil(float_arr): [ 2.  3.  4.  5. -1.]
np.trunc(float_arr): [ 1.  2.  3.  4. -1.]
------------------------------


#### 6. Aggregation Functions
- Functions that perform a computation on an array and return a single value (or fewer dimensions).

In [29]:
print("--- Aggregation Functions ---")
print(f"arr_large:\n{arr_large}")

--- Aggregation Functions ---
arr_large:
[1 2 3 4 5 6 7 8 9]


In [30]:
# Basic aggregations
print(f"np.sum(arr_large): {np.sum(arr_large)}") # Sum of all elements
print(f"arr_large.sum(): {arr_large.sum()}") # Can also call as a method

np.sum(arr_large): 45
arr_large.sum(): 45


In [31]:
print(f"np.mean(arr_large): {np.mean(arr_large)}") # Mean (average)
print(f"arr_large.mean(): {arr_large.mean()}")

print(f"np.std(arr_large): {np.std(arr_large)}") # Standard deviation
print(f"np.var(arr_large): {np.var(arr_large)}") # Variance

print(f"np.min(arr_large): {np.min(arr_large)}") # Minimum value
print(f"np.max(arr_large): {np.max(arr_large)}") # Maximum value

print(f"np.argmin(arr_large): {np.argmin(arr_large)}") # Index of minimum value (flattened array)
print(f"np.argmax(arr_large): {np.argmax(arr_large)}") # Index of maximum value (flattened array)


np.mean(arr_large): 5.0
arr_large.mean(): 5.0
np.std(arr_large): 2.581988897471611
np.var(arr_large): 6.666666666666667
np.min(arr_large): 1
np.max(arr_large): 9
np.argmin(arr_large): 0
np.argmax(arr_large): 8


In [32]:
# Cumulative aggregations
print(f"np.cumsum(arr1): {np.cumsum(arr1)}") # Cumulative sum
print(f"np.cumprod(arr1): {np.cumprod(arr1)}") # Cumulative product


np.cumsum(arr1): [ 1  3  6 10]
np.cumprod(arr1): [ 1  2  6 24]


In [33]:
# Aggregations with boolean arrays
print(f"\nnp.sum(arr_bool1): {np.sum(arr_bool1)}") # Counts True values (True=1, False=0)
print(f"np.any(arr_bool1): {np.any(arr_bool1)}") # Check if any element is True
print(f"np.all(arr_bool1): {np.all(arr_bool1)}") # Check if all elements are True
print(f"np.all(arr_bool2): {np.all(arr_bool2)}")
print("-" * 20)


np.sum(arr_bool1): 2
np.any(arr_bool1): True
np.all(arr_bool1): False
np.all(arr_bool2): False
--------------------


In [35]:
# --- Axis Parameter ---
# Perform aggregations along specific dimensions (rows, columns, etc.)
# axis=0: Aggregate along rows (collapse rows, result per column)
# axis=1: Aggregate along columns (collapse columns, result per row)
# axis=None (default): Aggregate over the entire array

In [36]:
print("--- Aggregations with Axis Parameter ---")
print(f"arr_large:\n{arr_large}")

--- Aggregations with Axis Parameter ---
arr_large:
[1 2 3 4 5 6 7 8 9]


In [39]:
# print(f"\nSum along columns (axis=0): {arr_large.sum(axis=0)}") # Output: [12 15 18] (1+4+7, 2+5+8, 3+6+9)
# print(f"Sum along rows (axis=1): {arr_large.sum(axis=1)}") # Output: [ 6 15 24] (1+2+3, 4+5+6, 7+8+9)

# print(f"\nMean along columns (axis=0): {arr_large.mean(axis=0)}") # Output: [4. 5. 6.]
# print(f"Mean along rows (axis=1): {arr_large.mean(axis=1)}") # Output: [2. 5. 8.]

# print(f"\nMax along columns (axis=0): {arr_large.max(axis=0)}") # Output: [7 8 9]
# print(f"Max along rows (axis=1): {arr_large.max(axis=1)}") # Output: [3 6 9]

In [41]:
# # argmin/argmax return indices along the specified axis
# print(f"\nArgmax along columns (axis=0): {arr_large.argmax(axis=0)}") # Output: [2 2 2] (indices of max in each col)
# print(f"Argmax along rows (axis=1): {arr_large.argmax(axis=1)}") # Output: [2 2 2] (indices of max in each row)


In [43]:
# # Cumulative functions also work with axis
# print(f"\nCumsum along columns (axis=0):\n{arr_large.cumsum(axis=0)}")
# # Output:
# # [[ 1  2  3]
# #  [ 5  7  9]
# #  [12 15 18]]
# print(f"\nCumsum along rows (axis=1):\n{arr_large.cumsum(axis=1)}")
# # Output:
# # [[ 1  3  6]
# #  [ 4  9 15]
# #  [ 7 15 24]]
# print("-" * 30)