In [1]:
# Import the NumPy library
import numpy as np

# --- Create Sample Arrays ---
arr_1d = np.arange(12) # [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr_2d = arr_1d.reshape(3, 4)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
arr_a = np.array([[1, 2], [3, 4]])
arr_b = np.array([[5, 6]]) # Note shape (1, 2)

print("--- Sample Arrays ---")
print(f"arr_1d (shape {arr_1d.shape}):\n{arr_1d}")
print(f"arr_2d (shape {arr_2d.shape}):\n{arr_2d}")
print(f"arr_a (shape {arr_a.shape}):\n{arr_a}")
print(f"arr_b (shape {arr_b.shape}):\n{arr_b}")
print("-" * 30)


# --- 1. Reshaping Arrays ---

print("--- Reshaping ---")
# np.reshape(array, new_shape) or array.reshape(new_shape)
# Changes the shape without changing data. Total size must remain the same.
# Returns a new array (often a view if possible, otherwise a copy).

reshaped_4x3 = arr_1d.reshape(4, 3)
print(f"arr_1d reshaped to (4, 3):\n{reshaped_4x3}")
print(f"New shape: {reshaped_4x3.shape}")

# Use -1 to infer one dimension automatically
reshaped_2x6 = arr_1d.reshape(2, -1) # Infers 6 columns
print(f"\narr_1d reshaped to (2, -1) -> (2, 6):\n{reshaped_2x6}")
print(f"New shape: {reshaped_2x6.shape}")

reshaped_neg1x4 = arr_1d.reshape(-1, 4) # Infers 3 rows
print(f"\narr_1d reshaped to (-1, 4) -> (3, 4):\n{reshaped_neg1x4}")
print(f"New shape: {reshaped_neg1x4.shape}")

# Flattening arrays (collapsing to 1D)
# np.ravel(array): Returns a flattened 1D array. May return a view if possible.
raveled_arr = np.ravel(arr_2d)
# raveled_arr = arr_2d.ravel() # Equivalent method call
print(f"\narr_2d raveled:\n{raveled_arr}")
print(f"Shape: {raveled_arr.shape}")
# Modifying the raveled array (if it's a view) might change the original
# raveled_arr[0] = 99 # Uncomment to see potential effect on arr_2d

# array.flatten(): Returns a flattened 1D array. *Always* returns a copy.
flattened_arr = arr_2d.flatten()
print(f"\narr_2d flattened:\n{flattened_arr}")
print(f"Shape: {flattened_arr.shape}")
# Modifying the flattened array will NOT change the original
flattened_arr[0] = 88
print(f"Original arr_2d after modifying flattened copy:\n{arr_2d}") # arr_2d is unchanged
# Restore original value for consistency in later examples
arr_2d[0, 0] = 0
print("-" * 30)


# --- 2. Transposing Arrays ---

print("--- Transposing ---")
# np.transpose(array) or array.T
# Permutes the dimensions (e.g., rows become columns and vice versa).
# Returns a view of the original array.

print(f"Original arr_2d (shape {arr_2d.shape}):\n{arr_2d}")

transposed_arr = np.transpose(arr_2d)
# transposed_arr = arr_2d.T # Equivalent attribute access
print(f"\nTransposed arr_2d (shape {transposed_arr.shape}):\n{transposed_arr}")

# Modifying the transpose WILL affect the original
transposed_arr[0, 1] = 77
print(f"\nOriginal arr_2d after modifying transpose:\n{arr_2d}") # arr_2d[1, 0] is now 77
# Restore original value
arr_2d[1, 0] = 4

# Transposing a 1D array has no effect
print(f"\nOriginal arr_1d: {arr_1d}")
print(f"Transposed arr_1d: {arr_1d.T}") # Shape remains (12,)
print("-" * 30)


# --- 3. Changing Dimensions ---

print("--- Changing Dimensions ---")
# Adding dimensions of size 1

# Using np.newaxis or None during indexing
arr_1d_row = arr_1d[np.newaxis, :] # Add axis at the beginning -> shape (1, 12)
print(f"arr_1d made into a row vector (shape {arr_1d_row.shape}):\n{arr_1d_row}")

arr_1d_col = arr_1d[:, np.newaxis] # Add axis at the end -> shape (12, 1)
print(f"\narr_1d made into a column vector (shape {arr_1d_col.shape}):\n{arr_1d_col}")

# Using np.expand_dims(array, axis)
expanded_axis0 = np.expand_dims(arr_1d, axis=0) # Equivalent to arr_1d[np.newaxis, :]
print(f"\nnp.expand_dims(arr_1d, axis=0) (shape {expanded_axis0.shape})")
expanded_axis1 = np.expand_dims(arr_1d, axis=1) # Equivalent to arr_1d[:, np.newaxis]
print(f"np.expand_dims(arr_1d, axis=1) (shape {expanded_axis1.shape})")

# Removing dimensions of size 1
# np.squeeze(array, axis=None)
# Removes axes of length one. If axis is specified, only that axis is removed (if size 1).
squeezed_row = np.squeeze(arr_1d_row) # Removes the first axis -> shape (12,)
print(f"\nSqueezed row vector (shape {squeezed_row.shape}):\n{squeezed_row}")
squeezed_col = np.squeeze(arr_1d_col) # Removes the second axis -> shape (12,)
print(f"\nSqueezed column vector (shape {squeezed_col.shape}):\n{squeezed_col}")

# Squeeze doesn't affect dimensions > 1
squeezed_2d = np.squeeze(arr_2d)
print(f"\nSqueezing arr_2d (no dims of size 1) (shape {squeezed_2d.shape}):\n{squeezed_2d}")
print("-" * 30)


# --- 4. Joining Arrays ---

print("--- Joining Arrays ---")
# np.concatenate((arr1, arr2, ...), axis=0)
# Joins arrays along an existing axis. Arrays must have same shape except along the concatenation axis.

# Concatenate along rows (axis=0, default)
concatenated_rows = np.concatenate((arr_a, arr_b), axis=0)
print(f"arr_a:\n{arr_a}")
print(f"arr_b:\n{arr_b}")
print(f"\nConcatenated along rows (axis=0):\n{concatenated_rows}")
print(f"Shape: {concatenated_rows.shape}") # Output: (3, 2)

# Concatenate along columns (axis=1) - shapes must match along axis 0
arr_c = arr_a * 10
print(f"\narr_c:\n{arr_c}")
concatenated_cols = np.concatenate((arr_a, arr_c), axis=1)
print(f"\nConcatenated along columns (axis=1):\n{concatenated_cols}")
print(f"Shape: {concatenated_cols.shape}") # Output: (2, 4)

# np.vstack((arr1, arr2, ...)): Stack arrays vertically (row-wise). Equivalent to concatenate axis=0.
vstacked = np.vstack((arr_a, arr_b))
print(f"\nvstack((arr_a, arr_b)):\n{vstacked}")
print(f"Shape: {vstacked.shape}")

# np.hstack((arr1, arr2, ...)): Stack arrays horizontally (column-wise). Equivalent to concatenate axis=1 (for 2D).
hstacked = np.hstack((arr_a, arr_c))
print(f"\nhstack((arr_a, arr_c)):\n{hstacked}")
print(f"Shape: {hstacked.shape}")
print("-" * 30)


# --- 5. Splitting Arrays ---

print("--- Splitting Arrays ---")
# np.split(array, indices_or_sections, axis=0)
# Splits an array into multiple sub-arrays.
split_arr = np.arange(12)

# Split into N equal sections
split_3_sections = np.split(split_arr, 3) # Splits into 3 equal parts
print(f"Split into 3 sections:\n{split_3_sections}")
# Output: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# Split at specific indices
split_at_indices = np.split(split_arr, [3, 5, 9]) # Split before indices 3, 5, 9
print(f"\nSplit at indices [3, 5, 9]:\n{split_at_indices}")
# Output: [array([0, 1, 2]), array([3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]

# Splitting 2D arrays
print(f"\nOriginal arr_2d:\n{arr_2d}")
# np.vsplit(array, indices_or_sections): Split vertically (row-wise). Equivalent to split axis=0.
vsplit_2 = np.vsplit(arr_2d, [2]) # Split after row index 1 (before index 2)
print(f"\nvsplit at index 2:\n{vsplit_2}")
# Output: [array([[0, 1, 2, 3], [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# np.hsplit(array, indices_or_sections): Split horizontally (column-wise). Equivalent to split axis=1.
hsplit_2 = np.hsplit(arr_2d, [1, 3]) # Split before column indices 1 and 3
print(f"\nhsplit at indices [1, 3]:\n{hsplit_2}")
# Output: [array([[0],[4],[8]]), array([[1, 2],[5, 6],[9, 10]]), array([[ 3],[ 7],[11]])]
print("-" * 30)


# --- 6. Adding/Removing Elements (Use with Caution) ---
# These functions typically return NEW arrays (copies) and can be inefficient
# for large arrays compared to pre-allocating or using other methods.

print("--- Adding/Removing Elements (Caution: Often Inefficient) ---")
original_arr = np.array([1, 2, 3, 4])
print(f"Original array: {original_arr}")

# np.append(array, values, axis=None)
appended_arr = np.append(original_arr, [5, 6]) # Appends to flattened array by default
print(f"Appended [5, 6]: {appended_arr}")

# Appending to 2D array requires matching dimensions or specifying axis
print(f"\narr_a:\n{arr_a}")
print(f"arr_b:\n{arr_b}")
appended_rows = np.append(arr_a, arr_b, axis=0) # Append rows
print(f"Appended rows:\n{appended_rows}")

# np.insert(array, index, values, axis=None)
inserted_arr = np.insert(original_arr, 2, [99, 88]) # Insert before index 2
print(f"\nInserted [99, 88] at index 2: {inserted_arr}")

# np.delete(array, index, axis=None)
deleted_arr = np.delete(original_arr, [0, 3]) # Delete elements at indices 0 and 3
print(f"\nDeleted elements at indices 0, 3: {deleted_arr}")
print("-" * 30)


# --- 7. Repeating Elements ---

print("--- Repeating Elements ---")
arr_repeat = np.array([[1, 2], [3, 4]])
print(f"Original array for repeating:\n{arr_repeat}")

# np.tile(array, reps)
# Constructs an array by repeating the whole input array 'reps' times.
tiled_arr = np.tile(arr_repeat, 2) # Repeat the whole array twice horizontally
print(f"\nTiled (x2 horizontally):\n{tiled_arr}")
# Output: [[1 2 1 2]
#          [3 4 3 4]]

tiled_arr_2d = np.tile(arr_repeat, (2, 3)) # Repeat 2x vertically, 3x horizontally
print(f"\nTiled (2x vertically, 3x horizontally):\n{tiled_arr_2d}")
# Output: [[1 2 1 2 1 2]
#          [3 4 3 4 3 4]
#          [1 2 1 2 1 2]
#          [3 4 3 4 3 4]]

# np.repeat(array, repeats, axis=None)
# Repeats each *element* of an array.
repeated_elements = np.repeat(arr_repeat, 3) # Repeat each element 3 times (flattens by default)
print(f"\nRepeated elements (x3, flattened):\n{repeated_elements}")
# Output: [1 1 1 2 2 2 3 3 3 4 4 4]

repeated_rows = np.repeat(arr_repeat, 2, axis=0) # Repeat each row twice
print(f"\nRepeated rows (x2, axis=0):\n{repeated_rows}")
# Output: [[1 2]
#          [1 2]
#          [3 4]
#          [3 4]]

repeated_cols = np.repeat(arr_repeat, 3, axis=1) # Repeat each column three times
print(f"\nRepeated columns (x3, axis=1):\n{repeated_cols}")
# Output: [[1 1 1 2 2 2]
#          [3 3 3 4 4 4]]

# Can specify different repeats per element (if repeats is an array)
repeat_counts = [1, 3]
repeated_diff_cols = np.repeat(arr_repeat, repeat_counts, axis=1) # Repeat col 0 once, col 1 three times
print(f"\nRepeated columns with counts [1, 3]:\n{repeated_diff_cols}")
# Output: [[1 2 2 2]
#          [3 4 4 4]]
print("-" * 30)



--- Sample Arrays ---
arr_1d (shape (12,)):
[ 0  1  2  3  4  5  6  7  8  9 10 11]
arr_2d (shape (3, 4)):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr_a (shape (2, 2)):
[[1 2]
 [3 4]]
arr_b (shape (1, 2)):
[[5 6]]
------------------------------
--- Reshaping ---
arr_1d reshaped to (4, 3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
New shape: (4, 3)

arr_1d reshaped to (2, -1) -> (2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
New shape: (2, 6)

arr_1d reshaped to (-1, 4) -> (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New shape: (3, 4)

arr_2d raveled:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

arr_2d flattened:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)
Original arr_2d after modifying flattened copy:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------------------
--- Transposing ---
Original arr_2d (shape (3, 4)):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed arr_2d (shape (4, 3)):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3