In [1]:
# Import the NumPy library
import numpy as np

# --- Create Sample Matrices (2D Arrays) ---
# Ensure matrices are square for operations like determinant, inverse, eigenvalues
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 1],
              [2, 2]])

# For solving linear systems Ax = C
C = np.array([7, 18]) # Represents the right-hand side vector

# A non-square matrix for SVD
D = np.array([[1, 2, 3],
              [4, 5, 6]])

print("--- Sample Matrices ---")
print(f"Matrix A (shape {A.shape}):\n{A}")
print(f"\nMatrix B (shape {B.shape}):\n{B}")
print(f"\nVector C (shape {C.shape}): {C}")
print(f"\nMatrix D (shape {D.shape}):\n{D}")
print("-" * 30)


# --- 1. Matrix Multiplication / Dot Product ---
# np.dot(a, b) or the '@' operator (preferred for matrix multiplication in Python 3.5+)

print("--- Matrix Multiplication ---")
# Using np.dot()
dot_product = np.dot(A, B)
print(f"np.dot(A, B):\n{dot_product}")

# Using the @ operator
matmul_product = A @ B
print(f"\nA @ B:\n{matmul_product}")
# Output for both:
# [[ 9  5]
#  [23 11]]

# Dot product of a matrix and a vector
vec_product = A @ C # Treating C as a column vector implicitly in matmul
print(f"\nA @ C:\n{vec_product}") # Output: [ 43  93]
print("-" * 30)


# --- 2. Matrix Inverse ---
# np.linalg.inv(a)
# Computes the multiplicative inverse of a matrix.
# The matrix must be square and non-singular (determinant != 0).

print("--- Matrix Inverse ---")
try:
    A_inv = np.linalg.inv(A)
    print(f"Inverse of A (np.linalg.inv(A)):\n{A_inv}")
    # Output:
    # [[-2.   1. ]
    #  [ 1.5 -0.5]]

    # Verify: A @ A_inv should be close to the identity matrix
    identity_check = A @ A_inv
    print(f"\nVerification (A @ A_inv):\n{identity_check}")
    # Use np.allclose to check for near-equality due to floating point precision
    is_identity = np.allclose(identity_check, np.eye(A.shape[0]))
    print(f"Is close to identity matrix? {is_identity}") # Output: True

except np.linalg.LinAlgError as e:
    print(f"Could not compute inverse of A: {e}")

# Example of a singular matrix (determinant is 0)
singular_matrix = np.array([[1, 2], [2, 4]])
try:
    inv_singular = np.linalg.inv(singular_matrix)
    print(f"\nInverse of singular matrix:\n{inv_singular}")
except np.linalg.LinAlgError as e:
    print(f"\nError inverting singular matrix: {e}") # Output: Singular matrix
print("-" * 30)


# --- 3. Matrix Determinant ---
# np.linalg.det(a)
# Computes the determinant of a square matrix.

print("--- Matrix Determinant ---")
det_A = np.linalg.det(A)
print(f"Determinant of A (np.linalg.det(A)): {det_A:.2f}") # Output: -2.00

det_singular = np.linalg.det(singular_matrix)
print(f"Determinant of singular matrix: {det_singular:.2f}") # Output: 0.00
print("-" * 30)


# --- 4. Matrix Trace ---
# np.trace(a)
# Computes the sum of the diagonal elements of a matrix.

print("--- Matrix Trace ---")
trace_A = np.trace(A)
print(f"Trace of A (np.trace(A)): {trace_A}") # Output: 5 (1 + 4)

trace_B = np.trace(B)
print(f"Trace of B (np.trace(B)): {trace_B}") # Output: 7 (5 + 2)
print("-" * 30)


# --- 5. Eigenvalues and Eigenvectors ---
# np.linalg.eig(a)
# Computes the eigenvalues and right eigenvectors of a square matrix.
# Returns a tuple: (eigenvalues, eigenvectors)
# Eigenvectors are stored column-wise: eigenvectors[:, i] corresponds to eigenvalues[i].

print("--- Eigenvalues and Eigenvectors ---")
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues of A:\n{eigenvalues}")
print(f"\nEigenvectors of A (column-wise):\n{eigenvectors}")

# Verify: A @ v = lambda * v for an eigenvector v and eigenvalue lambda
for i in range(len(eigenvalues)):
    lambda_val = eigenvalues[i]
    v_vec = eigenvectors[:, i]
    left_side = A @ v_vec
    right_side = lambda_val * v_vec
    print(f"\nVerifying eigenvector {i+1}:")
    print(f"  A @ v = {left_side}")
    print(f"  lambda * v = {right_side}")
    print(f"  Are they close? {np.allclose(left_side, right_side)}")
print("-" * 30)


# --- 6. Singular Value Decomposition (SVD) ---
# np.linalg.svd(a, full_matrices=True)
# Factorizes the matrix a into U * Sigma * Vh, where U and Vh are unitary matrices,
# and Sigma is a 1D array of the singular values (non-negative).
# Vh is the conjugate transpose of V.
# Works for non-square matrices as well.

print("--- Singular Value Decomposition (SVD) ---")
print(f"Matrix D:\n{D}")
U, Sigma, Vh = np.linalg.svd(D)

print(f"\nU matrix (shape {U.shape}):\n{U}")
print(f"\nSigma (singular values) (shape {Sigma.shape}): {Sigma}")
print(f"\nVh matrix (V transpose) (shape {Vh.shape}):\n{Vh}")

# To reconstruct the original matrix (approximately), Sigma needs to be formed
# into a diagonal matrix of the correct shape.
Sigma_matrix = np.zeros(D.shape)
# Populate Sigma_matrix with Sigma values on the diagonal
min_dim = min(D.shape)
Sigma_matrix[:min_dim, :min_dim] = np.diag(Sigma)

print(f"\nSigma matrix (shape {Sigma_matrix.shape}):\n{Sigma_matrix}")

# Reconstruct D: U @ Sigma_matrix @ Vh
D_reconstructed = U @ Sigma_matrix @ Vh
print(f"\nReconstructed D (U @ Sigma_matrix @ Vh):\n{D_reconstructed}")
print(f"Is reconstructed D close to original? {np.allclose(D, D_reconstructed)}")
print("-" * 30)


# --- 7. Solving Linear Systems ---
# np.linalg.solve(a, b)
# Solves the linear system Ax = b for x, where A is a square matrix.

print("--- Solving Linear Systems (Ax = C) ---")
print(f"Matrix A:\n{A}")
print(f"Vector C: {C}")

try:
    x = np.linalg.solve(A, C)
    print(f"\nSolution x (np.linalg.solve(A, C)): {x}") # Output: [-4.  5.5]

    # Verify: A @ x should be close to C
    verification = A @ x
    print(f"\nVerification (A @ x): {verification}")
    print(f"Is A @ x close to C? {np.allclose(verification, C)}") # Output: True

except np.linalg.LinAlgError as e:
    print(f"\nCould not solve system: {e}") # e.g., if A is singular
print("-" * 30)


# --- 8. Calculating Norms ---
# np.linalg.norm(x, ord=None, axis=None)
# Calculates the vector or matrix norm.
# Common vector norms (ord parameter for vectors):
#   ord=2 (default): L2 norm (Euclidean norm) - sqrt(sum(x_i^2))
#   ord=1: L1 norm (Manhattan norm) - sum(|x_i|)
#   ord=np.inf: Max norm - max(|x_i|)
# Common matrix norms (ord parameter for matrices):
#   ord='fro': Frobenius norm - sqrt(sum(A_ij^2))
#   ord=np.inf: Max absolute row sum
#   ord=-np.inf: Min absolute row sum
#   ord=1: Max absolute column sum
#   ord=-1: Min absolute column sum
#   ord=2: Largest singular value
#   ord=-2: Smallest singular value

print("--- Calculating Norms ---")
vector = np.array([3, -4, 5])
print(f"Vector: {vector}")
norm_l2 = np.linalg.norm(vector) # Default ord=2
print(f"L2 norm (Euclidean): {norm_l2:.4f}") # sqrt(3^2 + (-4)^2 + 5^2) = sqrt(9+16+25) = sqrt(50) approx 7.0711
norm_l1 = np.linalg.norm(vector, ord=1)
print(f"L1 norm (Manhattan): {norm_l1}") # |3| + |-4| + |5| = 3 + 4 + 5 = 12
norm_inf = np.linalg.norm(vector, ord=np.inf)
print(f"Infinity norm (Max): {norm_inf}") # max(|3|, |-4|, |5|) = 5

print(f"\nMatrix A:\n{A}")
norm_fro = np.linalg.norm(A, ord='fro')
print(f"Frobenius norm: {norm_fro:.4f}") # sqrt(1^2+2^2+3^2+4^2) = sqrt(1+4+9+16) = sqrt(30) approx 5.4772
norm_mat_inf = np.linalg.norm(A, ord=np.inf)
print(f"Infinity norm (Max row sum): {norm_mat_inf}") # max( |1|+|2|, |3|+|4| ) = max(3, 7) = 7
norm_mat_1 = np.linalg.norm(A, ord=1)
print(f"1-norm (Max column sum): {norm_mat_1}") # max( |1|+|3|, |2|+|4| ) = max(4, 6) = 6
print("-" * 30)

--- Sample Matrices ---
Matrix A (shape (2, 2)):
[[1 2]
 [3 4]]

Matrix B (shape (2, 2)):
[[5 1]
 [2 2]]

Vector C (shape (2,)): [ 7 18]

Matrix D (shape (2, 3)):
[[1 2 3]
 [4 5 6]]
------------------------------
--- Matrix Multiplication ---
np.dot(A, B):
[[ 9  5]
 [23 11]]

A @ B:
[[ 9  5]
 [23 11]]

A @ C:
[43 93]
------------------------------
--- Matrix Inverse ---
Inverse of A (np.linalg.inv(A)):
[[-2.   1. ]
 [ 1.5 -0.5]]

Verification (A @ A_inv):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Is close to identity matrix? True

Error inverting singular matrix: Singular matrix
------------------------------
--- Matrix Determinant ---
Determinant of A (np.linalg.det(A)): -2.00
Determinant of singular matrix: 0.00
------------------------------
--- Matrix Trace ---
Trace of A (np.trace(A)): 5
Trace of B (np.trace(B)): 7
------------------------------
--- Eigenvalues and Eigenvectors ---
Eigenvalues of A:
[-0.37228132  5.37228132]

Eigenvectors of A (column-wise):
[