In [1]:
# Import the NumPy library
import numpy as np

# --- 1. The Concept of Broadcasting ---
# Broadcasting allows NumPy to perform element-wise operations on arrays
# of different shapes, provided they meet certain compatibility rules.
# The smaller array is conceptually "broadcast" across the larger array
# so that they have compatible shapes. This happens without actually
# making copies of the data in memory.

# --- 2. Broadcasting Rules ---
# When operating on two arrays, NumPy compares their shapes element-wise,
# starting from the *trailing* (rightmost) dimensions. Two dimensions
# are compatible when:
#   1. They are equal, OR
#   2. One of them is 1.
# If these conditions are not met for all dimensions, a ValueError is raised.
# If the arrays have a different number of dimensions, the shape of the
# array with fewer dimensions is *prepended* with ones on its left side
# until the shapes have the same length.

# --- 3. Example 1: Scalar and Array ---
# The simplest case. A scalar can be broadcast to match any array shape.
print("--- Example 1: Scalar and Array ---")
arr = np.array([1, 2, 3, 4])
scalar = 100

result = arr + scalar # scalar is broadcast to shape (4,)
print(f"Array (shape {arr.shape}): {arr}")
print(f"Scalar: {scalar}")
print(f"Result (arr + scalar): {result}") # Output: [101 102 103 104]
print(f"Result shape: {result.shape}") # Output: (4,)

arr_2d = np.array([[1, 2], [3, 4]])
result_2d = arr_2d * 5 # scalar is broadcast to shape (2, 2)
print(f"\nArray 2D (shape {arr_2d.shape}):\n{arr_2d}")
print(f"Scalar: 5")
print(f"Result (arr_2d * 5):\n{result_2d}")
# Output:
# [[ 5 10]
#  [15 20]]
print(f"Result shape: {result_2d.shape}") # Output: (2, 2)
print("-" * 30)


# --- 4. Example 2: 1D and 2D Array ---
print("--- Example 2: 1D and 2D Array ---")
matrix = np.arange(1, 10).reshape(3, 3)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
vector_row = np.array([10, 20, 30]) # Shape (3,)

print(f"Matrix (shape {matrix.shape}):\n{matrix}")
print(f"Vector Row (shape {vector_row.shape}): {vector_row}")

# Operation: matrix + vector_row
# Shapes:   (3, 3) vs (3,)
# 1. Prepend 1 to vector_row shape: (1, 3)
# 2. Compare dimensions right-to-left:
#    - Dim 1: 3 == 3 (Compatible)
#    - Dim 0: 3 vs 1 (Compatible, 1 is broadcast to 3)
# Result shape: (3, 3)
result = matrix + vector_row
print(f"\nResult (matrix + vector_row):\n{result}")
# Output: vector_row is added to *each row* of the matrix
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]
print(f"Result shape: {result.shape}")
print("-" * 20)

# --- Example 3: Column Vector and 2D Array ---
print("--- Example 3: Column Vector and 2D Array ---")
# To broadcast a column vector, it needs shape (N, 1)
vector_col = np.array([[100], [200], [300]]) # Shape (3, 1)

print(f"Matrix (shape {matrix.shape}):\n{matrix}")
print(f"Vector Column (shape {vector_col.shape}):\n{vector_col}")

# Operation: matrix + vector_col
# Shapes:   (3, 3) vs (3, 1)
# 1. Shapes have same number of dimensions.
# 2. Compare dimensions right-to-left:
#    - Dim 1: 3 vs 1 (Compatible, 1 is broadcast to 3)
#    - Dim 0: 3 == 3 (Compatible)
# Result shape: (3, 3)
result = matrix + vector_col
print(f"\nResult (matrix + vector_col):\n{result}")
# Output: vector_col is added to *each column* of the matrix
# [[101 102 103]
#  [204 205 206]
#  [307 308 309]]
print(f"Result shape: {result.shape}")
print("-" * 20)

# --- Example 4: Broadcasting Both Arrays ---
print("--- Example 4: Broadcasting Both Arrays ---")
a = np.array([0.0, 10.0, 20.0, 30.0]) # Shape (4,)
b = np.array([1.0, 2.0, 3.0])       # Shape (3,)

# To combine these using broadcasting to get a 2D result,
# we need to reshape them to compatible forms, like (4, 1) and (1, 3)

a_col = a[:, np.newaxis] # Reshape 'a' to a column vector (4, 1)
# [[ 0.]
#  [10.]
#  [20.]
#  [30.]]
b_row = b[np.newaxis, :] # Reshape 'b' to a row vector (1, 3) (already was effectively)
# [[1. 2. 3.]]

print(f"a_col (shape {a_col.shape}):\n{a_col}")
print(f"b_row (shape {b_row.shape}):\n{b_row}") # Note: np.array([1., 2., 3.]) has shape (3,)

# Operation: a_col + b_row
# Shapes:   (4, 1) vs (1, 3)
# 1. Shapes have same number of dimensions.
# 2. Compare dimensions right-to-left:
#    - Dim 1: 1 vs 3 (Compatible, 1 is broadcast to 3)
#    - Dim 0: 4 vs 1 (Compatible, 1 is broadcast to 4)
# Result shape: (4, 3)
result = a_col + b_row
print(f"\nResult (a_col + b_row):\n{result}")
# Output: Creates an outer addition
# [[ 1.  2.  3.]
#  [11. 12. 13.]
#  [21. 22. 23.]
#  [31. 32. 33.]]
print(f"Result shape: {result.shape}")
print("-" * 30)


# --- 5. Example 5: Incompatible Shapes ---
print("--- Example 5: Incompatible Shapes ---")
arr_a = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
arr_b = np.array([10, 20])              # Shape (2,)

print(f"arr_a (shape {arr_a.shape}):\n{arr_a}")
print(f"arr_b (shape {arr_b.shape}): {arr_b}")

# Operation: arr_a + arr_b
# Shapes:   (2, 3) vs (2,)
# 1. Prepend 1 to arr_b shape: (1, 2)
# 2. Compare dimensions right-to-left:
#    - Dim 1: 3 vs 2 (INCOMPATIBLE!) -> ValueError
try:
    result = arr_a + arr_b
except ValueError as e:
    print(f"\nError trying arr_a + arr_b: {e}")

# Another incompatible example
arr_c = np.arange(12).reshape(4, 3) # Shape (4, 3)
arr_d = np.arange(4)                # Shape (4,) -> (1, 4) after prepending

print(f"\narr_c (shape {arr_c.shape}):\n{arr_c}")
print(f"arr_d (shape {arr_d.shape}): {arr_d}")

# Operation: arr_c + arr_d
# Shapes:   (4, 3) vs (4,) -> (1, 4)
# 1. Prepend 1 to arr_d: (1, 4)
# 2. Compare dimensions right-to-left:
#    - Dim 1: 3 vs 4 (INCOMPATIBLE!) -> ValueError
try:
    result = arr_c + arr_d
except ValueError as e:
    print(f"\nError trying arr_c + arr_d: {e}")

# To make arr_c and arr_d compatible for addition (e.g., add arr_d to each column),
# arr_d needs to be reshaped to (4, 1)
arr_d_col = arr_d[:, np.newaxis] # Shape (4, 1)
print(f"\narr_d_col (shape {arr_d_col.shape}):\n{arr_d_col}")
result_compatible = arr_c + arr_d_col
print(f"\nResult (arr_c + arr_d_col):\n{result_compatible}")
print(f"Result shape: {result_compatible.shape}") # Output: (4, 3)
print("-" * 30)

--- Example 1: Scalar and Array ---
Array (shape (4,)): [1 2 3 4]
Scalar: 100
Result (arr + scalar): [101 102 103 104]
Result shape: (4,)

Array 2D (shape (2, 2)):
[[1 2]
 [3 4]]
Scalar: 5
Result (arr_2d * 5):
[[ 5 10]
 [15 20]]
Result shape: (2, 2)
------------------------------
--- Example 2: 1D and 2D Array ---
Matrix (shape (3, 3)):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector Row (shape (3,)): [10 20 30]

Result (matrix + vector_row):
[[11 22 33]
 [14 25 36]
 [17 28 39]]
Result shape: (3, 3)
--------------------
--- Example 3: Column Vector and 2D Array ---
Matrix (shape (3, 3)):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector Column (shape (3, 1)):
[[100]
 [200]
 [300]]

Result (matrix + vector_col):
[[101 102 103]
 [204 205 206]
 [307 308 309]]
Result shape: (3, 3)
--------------------
--- Example 4: Broadcasting Both Arrays ---
a_col (shape (4, 1)):
[[ 0.]
 [10.]
 [20.]
 [30.]]
b_row (shape (1, 3)):
[[1. 2. 3.]]

Result (a_col + b_row):
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
Res