In [1]:
# Import the NumPy library
import numpy as np

In [2]:
# --- Create Sample Arrays ---

In [14]:
# 1D array of integers
arr1d = np.arange(6)

# 2D array of floats
arr2d = np.linspace(0, 1, 6).reshape(2, 3) # Reshape into 2 rows, 3 columns

# 3D array with a specific data type (boolean)
arr3d = np.random.rand(2, 3, 2) > 0.5 # 2 matrices, each 3x2, with True/False

print("--- Sample Arrays ---")
print("arr1d:\n", arr1d)
print("\narr2d:\n", arr2d)
print("\narr3d:\n", arr3d)
print("-" * 30)

--- Sample Arrays ---
arr1d:
 [0 1 2 3 4 5]

arr2d:
 [[0.  0.2 0.4]
 [0.6 0.8 1. ]]

arr3d:
 [[[False  True]
  [False  True]
  [ True  True]]

 [[False  True]
  [False  True]
  [ True False]]]
------------------------------


## 1. Key Array Attributes

In [15]:
print("--- Attributes of arr2d ---")

--- Attributes of arr2d ---


In [22]:
# ndarray.ndim: Number of array dimensions (axes)
print(f"Number of dimensions (ndim): {arr2d.ndim}") # Output: 2

# ndarray.shape: Tuple of array dimensions (rows, columns, etc.)
print(f"Shape (shape): {arr2d.shape}") # Output: (2, 3)

# ndarray.size: Total number of elements in the array
print(f"Total number of elements (size): {arr2d.size}") # Output: 6 (2 * 3)

# ndarray.dtype: Data type object describing the elements
print(f"Data type (dtype): {arr2d.dtype}") # Output: float64

# ndarray.itemsize: Size in bytes of each array element
print(f"Size of each element in bytes (itemsize): {arr2d.itemsize}") # Output: 8 (for float64)

# ndarray.nbytes: Total bytes consumed by the elements of the array (size * itemsize)
print(f"Total bytes consumed (nbytes): {arr2d.nbytes}") # Output: 48 (6 * 8)
print("-" * 30)

Number of dimensions (ndim): 2
Shape (shape): (2, 3)
Total number of elements (size): 6
Data type (dtype): float64
Size of each element in bytes (itemsize): 8
Total bytes consumed (nbytes): 48
------------------------------


In [23]:
print("--- Attributes of arr3d ---")
print(f"ndim: {arr3d.ndim}")       # Output: 3
print(f"shape: {arr3d.shape}")     # Output: (2, 3, 2)
print(f"size: {arr3d.size}")       # Output: 12 (2 * 3 * 2)
print(f"dtype: {arr3d.dtype}")     # Output: bool
print(f"itemsize: {arr3d.itemsize}") # Output: 1 (for bool)
print(f"nbytes: {arr3d.nbytes}")   # Output: 12 (12 * 1)
print("-" * 30)

--- Attributes of arr3d ---
ndim: 3
shape: (2, 3, 2)
size: 12
dtype: bool
itemsize: 1
nbytes: 12
------------------------------


## 2. Common Data Types (dtype)

- NumPy supports a wide range of numerical types. Some common ones:
- np.int8, np.int16, np.int32, np.int64: Signed integers of different sizes
- np.uint8, np.uint16, np.uint32, np.uint64: Unsigned integers
- np.float16, np.float32, np.float64: Floating-point numbers (half, single, double precision)
- np.complex64, np.complex128: Complex numbers
- np.bool_: Boolean type (True/False)
- np.object_: For Python objects (use sparingly, less efficient)
- np.string_: Fixed-length byte strings (use 'S' code, e.g., 'S10' for 10 bytes)
- np.unicode_: Fixed-length Unicode strings (use 'U' code, e.g., '<U5' for 5 characters)

In [25]:
# You can create arrays with specific dtypes:
int_arr = np.array([1, 2.5, 3], dtype=np.int16)
print("Integer array (int16):\n", int_arr)
print("dtype:", int_arr.dtype)

Integer array (int16):
 [1 2 3]
dtype: int16


In [26]:
float_arr = np.array([1.0, 2.5, 3.1], dtype=np.float32)
print("\nFloat array (float32):\n", float_arr)
print("dtype:", float_arr.dtype)


Float array (float32):
 [1.  2.5 3.1]
dtype: float32


In [27]:
bool_arr = np.array([0, 1, -1, 0.0], dtype=np.bool_) # Non-zero converts to True, zero to False
print("\nBoolean array from numbers:\n", bool_arr)
print("dtype:", bool_arr.dtype)
print("-" * 30)


Boolean array from numbers:
 [False  True  True False]
dtype: bool
------------------------------


## 3. Type Casting (astype method)
- Use ndarray.astype() to create a *new* array with a different dtype.
- The original array remains unchanged.

In [28]:
arr1d = np.arange(6)
float_from_int = arr1d.astype(np.float64)

print("Original int array (arr1d):\n", arr1d)
print("dtype:", arr1d.dtype, "\n")

print("\nCasted to float64:\n", float_from_int)
print("dtype:", float_from_int.dtype)
print("-" * 20)

Original int array (arr1d):
 [0 1 2 3 4 5]
dtype: int64 


Casted to float64:
 [0. 1. 2. 3. 4. 5.]
dtype: float64
--------------------


In [29]:
int_from_float = arr2d.astype(np.int32) # Decimals are truncated (not rounded)
print("Original float array (arr2d):\n", arr2d)
print("dtype:", arr2d.dtype, "\n")

print("\nCasted to int32 (truncates decimals):\n", int_from_float)
print("dtype:", int_from_float.dtype)
print("-" * 20)

Original float array (arr2d):
 [[0.  0.2 0.4]
 [0.6 0.8 1. ]]
dtype: float64 


Casted to int32 (truncates decimals):
 [[0 0 0]
 [0 0 1]]
dtype: int32
--------------------


In [30]:
bool_from_int = arr1d.astype(np.bool_) # 0 becomes False, non-zero becomes True
print("Original int array (arr1d):\n", arr1d)
print("dtype:", arr1d.dtype, "\n")

print("\nCasted to bool:\n", bool_from_int)
print("dtype:", bool_from_int.dtype)
print("-" * 20)

Original int array (arr1d):
 [0 1 2 3 4 5]
dtype: int64 


Casted to bool:
 [False  True  True  True  True  True]
dtype: bool
--------------------


In [31]:
string_from_float = arr2d.astype(str) # Or use np.string_ or np.unicode_
print("Original float array (arr2d):\n", arr2d)
print("dtype:", arr2d.dtype, "\n")

print("\nCasted to string:\n", string_from_float)
print("dtype:", string_from_float.dtype) # Often '<U32' or similar (unicode string)
print("-" * 20)

Original float array (arr2d):
 [[0.  0.2 0.4]
 [0.6 0.8 1. ]]
dtype: float64 


Casted to string:
 [['0.0' '0.2' '0.4']
 ['0.6000000000000001' '0.8' '1.0']]
dtype: <U32
--------------------


##### Be careful when casting:
- Float to Int: Truncation occurs.
- Casting larger types (e.g., float64) to smaller types (e.g., float16 or int8)
- can lead to loss of precision or overflow/underflow if values are outside the smaller type's range.

In [33]:
large_float = np.array([1e10, 2e-10], dtype=np.float64)
print("Large float array (float64):\n", large_float, "\n")

small_float = large_float.astype(np.float16)
print("Casted to float16 (potential precision loss):\n", small_float)

Large float array (float64):
 [1.e+10 2.e-10] 

Casted to float16 (potential precision loss):
 [inf  0.]


C:\Users\ranji\AppData\Local\Temp\ipykernel_14448\4157310201.py:4: RuntimeWarning: overflow encountered in cast
  small_float = large_float.astype(np.float16)


In [34]:
# Invalid casting can raise errors (e.g., string 'abc' to int)
# numeric_string = np.array(['1', '2', '3'])
# int_from_numeric_string = numeric_string.astype(np.int32) # This works
# print("\nInt from numeric string:\n", int_from_numeric_string)

# non_numeric_string = np.array(['1', 'two', '3'])
# try:
#     int_from_non_numeric_string = non_numeric_string.astype(np.int32)
# except ValueError as e:
#     print(f"\nError casting non-numeric string to int: {e}") # This will raise ValueError
